### ISSUE TITLE
Error downloading multiple files

### ISSUE THREAD

**Issue by mrkacg1** [cubiclesoft/js-fileexplorer#13]
Hello. When downloading multiple files, it tells me that the zip file is not correct or contains errors.

It happens with PDF, sometimes with .docx

Unable to open the downloaded zip when selecting an entire folder or selecting multiple files.

**Comment by mrkacg1** [comment]
Please let me know what details you need. I will attach a zip file. It says that the files inside are damaged, when in fact it is not.

http://u.pc.cd/Cr17

**Comment by cubiclesoft** [comment]
Opening that file in a hex editor shows that the word "Array" has been output as the first few bytes.  There's something wrong with your server-side code.  PHP generally outputs the word "Array" when there is an `echo` statement and is passed an array instead of a string.

Crash course on structured binary files:

https://www.youtube.com/watch?v=Chsuicg4d7k

By details, I mean following the standard procedure when opening an issue on an issue tracker to provide:  Details of the problem being encountered, how to replicate it, and also mininal source code that demonstrates the problem.  The JS File Explorer widget itself is a pure Javascript widget that runs in the browser.  It has no knowledge of how to generate ZIP files.  The server side helper, if used, may emit ZIP files but the underlying [ZIPStreamWriter class](https://github.com/cubiclesoft/php-zipstreamwriter) is a completely different project.  It helps to narrow down a problem on your end such that it can be easily replicated on the developer's side of things.

**Comment by mrkacg1** [comment]
I am using this copy:

https://github.com/cubiclesoft/php-filemanager

No modifications are made, only the routes are configured from the install.php

After installing, I can't download the zip files.

**Comment by cubiclesoft** [comment]
I'm unable to replicate this issue.  PHP File Manager is a separate product that uses JS File Explorer.  I've tried replicating this on personal and production systems running PHP File Manager, various PHP configurations, etc.  In all cases, a valid ZIP file is generated.

You're going to have to dig into it on your side to see where that "Array" is being emitted from.

**Comment by mrkacg1** [comment]
Perfect, could you give me a clue to start where that array comes from?

**Comment by mrkacg1** [comment]
Well, I've been testing and still can't see the error. There are no error logs when generating the .zip file

It is very strange because it only happens with .doc, .pdf and other files. It doesn't happen with images, neither with .js or .css files

**Comment by mrkacg1** [comment]
Hello:

-Apache 2.4.5 on Linux
-PHP 7.0.33
-It is running locally

The individual download is successful, but when selecting multiple files to download, an error appears in the .zip file

It only happens with .pdf, .doc, .xls files. That is, with documents.

**Comment by cubiclesoft** [comment]
Hmm.  PHP 7.0.33 is fairly old (released in 2018) and no longer has any support from any upstream.  The version of Apache you are running is even older (released in 2013).  Both products have had major security fixes and changes in the interim.  I don't have an easy way to test multiple PHP versions.

**Comment by mrkacg1** [comment]
I understand, then you can tell me with what specifications you carry out the tests, so I can carry them out too. It would be important if you can test multiple .pdf or .docx documents. That is where the problem arises. Thank you and I hope to help make the product much better.

**Comment by cubiclesoft** [comment]
You need to upgrade to actively supported versions of PHP and Apache.  I did test with several .pdf and .docx files under both PHP 7.4 and 8.1 series and had no issues with ZIP file generation.

**Comment by mrkacg1** [comment]
Confirmed, the problem was the version of php. I have tested with version 8.1.6 and it works
