### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by natesworksog** [cubiclesoft/js-fileexplorer#22]
Doesn't work on linux.

**Comment by cubiclesoft** [comment]
That's really broad.  Linux is a massive ecosystem of hundreds, if not thousands, of distros all packaged a gazillion different ways.  Linux itself has no GUI as it is just the monolithic kernel.  A GUI is provided by windowing systems like Gnome, KDE, XFCE, etc. and those sit on top of servers like X and Wayland.  And web browsers like Chromium and Firefox generally operate only within a GUI environment or minimally simulated GUI environment (e.g. PhantomJS, Puppeteer).

Opening an issue and saying something doesn't work without providing details is...unhelpful.  You need to provide a lot more information/details about what specifically is not working.  Firefox and Chrome are pretty universal web browsers that form a unified presentation layer across all supported ecosystems, so those should theoretically work with the widget.  Alternate web browsers like Konquerer might not work as well.  Using this widget is not magical as it requires a bunch of work to integrate it into a software product - the widget provides the view of and interactivity for a hierarchical file/object system but it is up to you to provide the rest.

Closing this issue due to not having sufficient details.  Will reopen if sufficient details become available.
