### ISSUE TITLE
如何在右键菜单添加新的选项

### ISSUE THREAD

**Issue by 878862905** [cubiclesoft/js-fileexplorer#25]
如何在右键菜单添加新的选项

**Comment by cubiclesoft** [comment]
The right-click menu is whatever the web browser provides given the context in which it is used.  There is no custom right-click menu at this time.

Note that I only speak English and used Google Translate for the above to figure out what was being requested.  Google Translate is not very good at translating text so hopefully I am understanding the request.  Closing since this is not an issue with JS File Explorer itself.
