### ISSUE TITLE
Mouse right click freezes the UI for a few seconds before you can use it.

### ISSUE THREAD

**Issue by navdeepghai** [cubiclesoft/js-fileexplorer#27]
I tried to select a few files by using "Control+Mouse Click" but It freezes the screen without any warning.

**Comment by cubiclesoft** [comment]
Seems fine to me.  Please provide reasonable steps to replicate the issue.

Closing for now.

**Comment by pablonunez** [comment]
I also experience it in Chrome and Firefox. I think it is closely related to the issue you mentioned in the 'Known Limitations' section. I have resolved it because in my case, I only use the component in read-only mode and don't need to copy/move/... 

In my case, I commented out the lines on StartSelectionHandler that control the right-click of the mouse. Perhaps this case could be parameterized:

```
// Enable right-click context menu.
if (e.button == 2)
{
	// elems.itemsclipboardoverlay.value = '   ';
	// elems.itemsclipboardoverlaypastewrap.classList.remove('fe_fileexplorer_hidden');
	// elems.itemsclipboardoverlaypastewrap.classList.add('fe_fileexplorer_items_clipboard_contextmenu');
}
```
